MONGODB_HOST: mongodb-{{ env }}.devops90s.shop
REDIS_HOST: redis-{{ env }}.devops90s.shop
MYSQL_HOST: mysql-{{ env }}.devops90s.shop 
RABBITMQ_HOST: rabbitmq-{{ env }}.devops90s.shop 
CATALOGUE_HOST: catalogue.backend-alb-{{ env }}.devops90s.shop
USER_HOST: user.backend-alb-{{ env }}.devops90s.shop
CART_HOST: cart.backend-alb-{{ env }}.devops90s.shop
SHIPPING_HOST: shipping.backend-alb-{{ env }}.devops90s.shop
PAYMENT_HOST: payment.backend-alb-{{ env }}.devops90s.shop
